# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Copy the templates directory into the container
COPY templates /app/templates

# Install dependencies
RUN pip install Flask requests

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run frontend.py when the container launches
CMD ["python", "frontend.py"]
