apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-frontend
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-frontend
  template:
    metadata:
      labels:
        app: flask-frontend
    spec:
      containers:
      - name: flask-frontend
        image: gcr.io/c0893970/flask-frontend
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-frontend-service
  namespace: frontend
spec:
  type: LoadBalancer
  selector:
    app: flask-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
